import { useId, useLayoutEffect, useMemo, useRef, useState } from "react";
import katex from "katex";
import "katex/dist/katex.min.css";
import { latexPreview } from "../../math";
import "./MathExpressionInput.css";

/**
 * An answer field for algebraic expressions: the learner types ordinary
 * notation (`x^2 + 3x + 7`) and sees it set as mathematics, live, underneath.
 *
 * **The learner is never asked to write LaTeX** — and, more to the point, is
 * never *able* to. Everything typed goes through `parseExpression`, and the
 * TeX handed to KaTeX is generated by `toLatex` from the resulting AST, a
 * closed set of node kinds. This is what keeps `EquationBlock`'s standing rule
 * (KaTeX is only ever given trusted TeX) true for learner-derived input.
 *
 * **On the `dangerouslySetInnerHTML` below.** It renders KaTeX's own output,
 * and its safety rests on two invariants that are asserted in
 * `src/math/__tests__/expression.test.ts` § "the injection surface", not left
 * as a claim here:
 *
 *  1. the tokenizer's character allowlist rejects `<`, `>`, `&`, `"` and `\`
 *     outright, so a hostile string fails to parse and never produces an AST
 *     (the suite fires a battery of them — script tags, `\href{javascript:}`,
 *     attribute-breakout attempts — and requires every one to be refused);
 *  2. for any input that DOES parse, the emitted TeX is checked to contain no
 *     markup characters and no command outside a fixed inert vocabulary —
 *     `\href`, `\url`, `\includegraphics`, `\def` and friends are impossible
 *     to emit, and the only source-derived text in the output is an identifier
 *     name already constrained to `[A-Za-z](_[A-Za-z0-9]+)?`.
 *
 * KaTeX is additionally called with `trust: false`, which refuses the
 * URL-bearing commands even if one ever did reach it. A sanitizer is not the
 * right tool here: the input is not HTML being cleaned, it is a grammar whose
 * accepted language cannot express markup in the first place. If either
 * invariant above is ever relaxed — a new node kind, a wider name pattern —
 * that test is where it will fail.
 *
 * **The preview is a correctness surface, not decoration.** Infix notation is
 * ambiguous — `1/2x` has two defensible readings — and the rendered form is
 * how the learner discovers which one they got before submitting. A field that
 * silently picked a reading would be worse than one that refuses to guess. For
 * the same reason the preview shows the PARSE, never the raw text prettified.
 *
 * The palette exists because the alternative is worse, not because more
 * buttons are better: a learner who does not know that `sqrt(x)` is spelled
 * that way has no way to discover it from an empty box. It offers the symbols
 * an item actually needs (its declared variables first), and inserts at the
 * caret rather than appending, so it composes with typing instead of fighting
 * it.
 */

export type MathExpressionInputProps = {
  value: string;
  onChange: (next: string) => void;
  /** Declared variables for this item — offered first in the palette. */
  variables?: readonly string[];
  /** Extra item-specific symbols worth offering. */
  palette?: readonly string[];
  placeholder?: string;
  /** Accessible name for the field. */
  label: string;
  disabled?: boolean;
  /** Submit on Enter (the surrounding form's usual behaviour). */
  onSubmit?: () => void;
};

type PaletteEntry = {
  /** What the button shows. */
  readonly label: string;
  /** What gets inserted. */
  readonly insert: string;
  /** Where the caret lands afterwards, counted back from the end of `insert`. */
  readonly caretFromEnd?: number;
  readonly title: string;
};

const OPERATION_ENTRIES: readonly PaletteEntry[] = [
  { label: "x²", insert: "^2", title: "Raise to a power" },
  { label: "xⁿ", insert: "^", title: "Raise to any power" },
  { label: "a/b", insert: "/", title: "Divide" },
  { label: "√", insert: "sqrt()", caretFromEnd: 1, title: "Square root" },
  { label: "( )", insert: "()", caretFromEnd: 1, title: "Group" },
  { label: "×", insert: "*", title: "Multiply" },
  { label: "|a|", insert: "abs()", caretFromEnd: 1, title: "Absolute value" },
  { label: "π", insert: "pi", title: "Pi" },
  { label: "sin", insert: "sin()", caretFromEnd: 1, title: "Sine" },
  { label: "cos", insert: "cos()", caretFromEnd: 1, title: "Cosine" },
  { label: "ln", insert: "ln()", caretFromEnd: 1, title: "Natural logarithm" },
  { label: "eˣ", insert: "exp()", caretFromEnd: 1, title: "Exponential" },
];

function renderTex(tex: string): string | null {
  try {
    return katex.renderToString(tex, {
      displayMode: false,
      throwOnError: true,
      strict: "ignore",
      output: "htmlAndMathml",
      trust: false,
    });
  } catch {
    return null;
  }
}

export function MathExpressionInput({
  value,
  onChange,
  variables = [],
  palette = [],
  placeholder,
  label,
  disabled = false,
  onSubmit,
}: MathExpressionInputProps) {
  const inputRef = useRef<HTMLInputElement | null>(null);
  // Whether the field has EVER been focused. Needed because selectionStart on
  // a never-focused text input is 0, not null (null is reserved for input
  // types without selection), so the `?? value.length` fallback below never
  // fired and a palette click on a restored draft PREPENDED at position 0 —
  // review finding against the original comment's wrong claim.
  const hasFocusedRef = useRef(false);
  const [paletteOpen, setPaletteOpen] = useState(false);
  const previewId = useId();
  const paletteId = useId();

  const outcome = useMemo(() => latexPreview(value), [value]);
  const html = useMemo(
    () => (outcome.ok && outcome.latex ? renderTex(outcome.latex) : null),
    [outcome],
  );

  const entries = useMemo<readonly PaletteEntry[]>(() => {
    // Deduped by insert string (variables win over palette, palette over
    // operations) — a config that lists a symbol as both a variable and a
    // palette extra previously rendered TWO identical keys with colliding
    // React keys (review finding: console errors on every keystroke).
    const seen = new Set<string>();
    const out: PaletteEntry[] = [];
    const push = (entry: PaletteEntry) => {
      if (seen.has(entry.insert)) return;
      seen.add(entry.insert);
      out.push(entry);
    };
    for (const name of variables) push({ label: name, insert: name, title: `Insert ${name}` });
    for (const symbol of palette) push({ label: symbol, insert: symbol, title: `Insert ${symbol}` });
    for (const entry of OPERATION_ENTRIES) push(entry);
    return out;
  }, [variables, palette]);

  // Where the caret must land once React has COMMITTED the inserted text.
  //
  // This was a `requestAnimationFrame` callback, which failed in a real
  // browser (and only there — jsdom's synchronous re-render hid it): the frame
  // could fire before React committed the new value, so the caret was set
  // against the OLD string and the subsequent commit pushed it back to the
  // end. Typing after inserting `sqrt()` then continued outside the
  // parentheses instead of inside them. A layout effect is the ordering
  // guarantee this actually needs — it runs after the DOM holds the new value.
  const [pendingCaret, setPendingCaret] = useState<number | null>(null);

  useLayoutEffect(() => {
    if (pendingCaret === null) return;
    const el = inputRef.current;
    if (el) {
      el.focus();
      el.setSelectionRange(pendingCaret, pendingCaret);
    }
    setPendingCaret(null);
  }, [pendingCaret]);

  const insert = (entry: PaletteEntry) => {
    const field = inputRef.current;
    // Append when the field has never been focused (its selectionStart is a
    // meaningless 0 then, not null) or the position is unavailable.
    const start = hasFocusedRef.current ? (field?.selectionStart ?? value.length) : value.length;
    const end = hasFocusedRef.current ? (field?.selectionEnd ?? value.length) : value.length;
    onChange(value.slice(0, start) + entry.insert + value.slice(end));
    setPendingCaret(start + entry.insert.length - (entry.caretFromEnd ?? 0));
  };

  const isBlank = value.trim().length === 0;

  return (
    <div className="math-expression">
      <div className="math-expression__row">
        <input
          ref={inputRef}
          className="math-expression__field"
          type="text"
          inputMode="text"
          autoComplete="off"
          autoCorrect="off"
          autoCapitalize="off"
          spellCheck={false}
          // Bounds the parser's input; with the parser's own depth guard this
          // is belt-and-braces against pathological pastes, and no honest
          // answer at this course's level approaches it.
          maxLength={200}
          onFocus={() => {
            hasFocusedRef.current = true;
          }}
          aria-label={label}
          aria-describedby={previewId}
          aria-invalid={!isBlank && !outcome.ok}
          placeholder={placeholder ?? "e.g. x^2 + 3x + 7"}
          value={value}
          disabled={disabled}
          onChange={(event) => onChange(event.target.value)}
          onKeyDown={(event) => {
            if (event.key === "Enter" && onSubmit) {
              event.preventDefault();
              onSubmit();
            }
          }}
        />
        <button
          type="button"
          className="math-expression__palette-toggle"
          aria-expanded={paletteOpen}
          aria-controls={paletteId}
          disabled={disabled}
          onClick={() => setPaletteOpen((open) => !open)}
        >
          <span aria-hidden="true">√x</span>
          <span className="sr-only">
            {paletteOpen ? "Hide symbols and operations" : "Show symbols and operations"}
          </span>
        </button>
      </div>

      {/*
        One live region for all three states, so a screen reader hears the
        parse change as the learner types rather than only on submit. `polite`
        because it updates on every keystroke.
      */}
      <div className="math-expression__preview" id={previewId} aria-live="polite">
        {isBlank ? (
          <span className="math-expression__hint">
            Type it the ordinary way — <code>x^2</code>, <code>3x</code>, <code>(x+1)/2</code>,{" "}
            <code>sqrt(x)</code>. It will be set as mathematics here.
          </span>
        ) : outcome.ok && html ? (
          <>
            <span className="sr-only">Your answer, as read: </span>
            <span
              className="math-expression__rendered"
              // Generated by `toLatex` from a parsed AST — never learner text.
              dangerouslySetInnerHTML={{ __html: html }}
            />
          </>
        ) : (
          <span className="math-expression__error" role="status">
            {outcome.ok
              ? "That parsed, but could not be typeset."
              : outcome.message}
          </span>
        )}
      </div>
      {paletteOpen && (
        <div className="math-expression__palette" id={paletteId} role="group" aria-label="Symbols and operations">
          {entries.map((entry) => (
            <button
              key={`${entry.label}:${entry.insert}`}
              type="button"
              className="math-expression__key"
              title={entry.title}
              disabled={disabled}
              onClick={() => insert(entry)}
            >
              {entry.label}
            </button>
          ))}
        </div>
      )}

    </div>
  );
}
