#!/usr/bin/env node

import { spawn } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const TOOL_ROOT = join(ROOT, "tools", "motion-authoring");
const GENERATED = join(TOOL_ROOT, ".generated");
const sceneModules = JSON.parse(
  readFileSync(
    join(ROOT, "scripts", "animation-authoring-scenes.json"),
    "utf8",
  ),
);

function parseArgs(argv) {
  const result = { scene: "", port: 9000, open: true };
  for (let index = 0; index < argv.length; index += 1) {
    const argument = argv[index];
    if (argument === "--scene") result.scene = argv[++index] ?? "";
    else if (argument === "--port") result.port = Number(argv[++index]);
    else if (argument === "--no-open") result.open = false;
    else if (argument === "--list") {
      console.log(Object.keys(sceneModules).join("\n"));
      process.exit(0);
    } else {
      throw new Error(`Unknown animate option: ${argument}`);
    }
  }
  if (!result.scene) {
    throw new Error(
      "Missing --scene <production-scene-id>. Use --list to see valid IDs.",
    );
  }
  if (result.scene === "transform-spike") {
    throw new Error(
      '"transform-spike" is development-only and cannot be opened through the production authoring registry.',
    );
  }
  if (!(result.scene in sceneModules)) {
    throw new Error(
      `Unknown production scene "${result.scene}". Valid IDs:\n  ${Object.keys(
        sceneModules,
      ).join("\n  ")}`,
    );
  }
  if (
    !Number.isInteger(result.port) ||
    result.port < 1 ||
    result.port > 65535
  ) {
    throw new Error("--port must be an integer from 1 to 65535.");
  }
  return result;
}

function writeSelectedProject(sceneId) {
  const scene = sceneModules[sceneId];
  mkdirSync(GENERATED, { recursive: true });
  writeFileSync(
    join(GENERATED, "selectedScene.ts"),
    [
      "// Generated by scripts/animate-scene.mjs; do not edit.",
      `export {${scene.exportName} as default} from "../../../src/guided-scenes/scenes/${scene.module}";`,
      "",
    ].join("\n"),
  );
  const authoringImports =
    sceneId === "matrix-transformations"
      ? [
          'import authoringPlugin from "../src/editorPlugin";',
          'import {MATRIX_TRANSFORMATION_PROJECT_VARIABLES} from "../../../src/guided-scenes/authoring/matrixTransformationTuning";',
        ]
      : [];
  const authoringSettings =
    sceneId === "matrix-transformations"
      ? [
          "  plugins: [authoringPlugin()],",
          "  variables: MATRIX_TRANSFORMATION_PROJECT_VARIABLES,",
          "  experimentalFeatures: true,",
        ]
      : [];
  writeFileSync(
    join(GENERATED, "project.ts"),
    [
      "// Generated by scripts/animate-scene.mjs; do not edit.",
      'import {makeProject} from "@motion-canvas/core";',
      'import selectedScene from "./selectedScene?scene";',
      ...authoringImports,
      "",
      "export default makeProject({",
      `  name: "production:${sceneId}",`,
      "  scenes: [selectedScene],",
      ...authoringSettings,
      "});",
      "",
    ].join("\n"),
  );
}

function main() {
  const options = parseArgs(process.argv.slice(2));
  writeSelectedProject(options.scene);
  const vite = join(TOOL_ROOT, "node_modules", "vite", "bin", "vite.js");
  const args = [
    vite,
    "--host",
    "127.0.0.1",
    "--port",
    String(options.port),
    "--strictPort",
  ];
  if (options.open) args.push("--open");
  console.log(
    `Opening native Motion Canvas editor for ${options.scene} at http://127.0.0.1:${options.port}`,
  );
  const child = spawn(process.execPath, args, {
    cwd: TOOL_ROOT,
    stdio: "inherit",
  });
  child.on("exit", (code, signal) => {
    if (signal) process.kill(process.pid, signal);
    process.exit(code ?? 1);
  });
}

try {
  main();
} catch (error) {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
}
